### ISSUE TITLE
La traducción no funciona con la versión 4.7.4

### ISSUE THREAD

**Issue by javierriveracastro** [allnnde/pf2e-esp-translation#1]
Buenas, no parece que la traducción funcione con la última versión del sistema. Es necesario actualizarla.

También he visto que estas traduciendo los compendios, y me temo que eso es muy difícil (lo sé porque lo hemos intentando un grupo de entre 4 y 8 personas del Discord oficial en español y fracasado miserablemente). Estamos intentando hacer una traducción con DeepL usando los scripts de los franceses, si te interesa o necesitas ayuda puedes pasar por nuestro discord (https://discord.gg/F3qkbGrz)

Si quieres ayuda o aceptas pull request para las traducciones del sistema (no de los compendios), avisa que igual podemos encontrar ayuda.

**Comment by allnnde** [comment]
Buenas,c omo pude comentar en el discord, en esta semana esta viendo el error aver si puedo solucionarlo, soy nuevo en todo esto de foundy y aun no conozco todo

De momento mi idea era ir traducciondo las clases y habilidades para poder usarlos rapidamente ya que, apesar que sean compendio he visto con mis jugadores que nos sirve. si les parece podriamos coordinar para ver como seria para hacer tambien a nivel de sistema para ir complementando. ya quie entiendo que ustedes tambien tiene una traduccion
