### ISSUE TITLE
Duda con respecto a una traducción.

### ISSUE THREAD

**Issue by SilkyKori247** [allnnde/pf2e-esp-translation#154]
Saludos! He notado de que la sección de "Pronouns" ha sido traducida como "Sexo", en ves de "Pronombres", que sería una traducción no sólo más directa, sino más adecuada, debido a de que los pronombres y el sexo son dos aspectos que tienen formas muy distintas de ser aplicadas. Tuve el caso de que, al traducir un personaje, sus "Pronouns" eran "She/Her", pero al aplicar la traducción, resulta que era su "Sexo", algo que no se formatea como "Ella". No es mayor problema, solamente pienso de que hay un término para ahorrar este inconveniente.

Sugiero que se haga el cambio, para una traducción más precisa y menos acomplejada, pero me gustaría saber si hay alguna razón por la que esta decisión fué tomada que tal vez no consideré. 

Admiro mucho su trabajo, y espero con anhelo su respuesta!

**Comment by allnnde** [comment]
razon como tal no ahi, solo es la traduccion autoatica que se hizo en su momento, lo cambiaremos
