### ISSUE TITLE
cant import some clases

### ISSUE THREAD

**Issue by Keneg11** [allnnde/pf2e-esp-translation#200]
cant import some clases, sorcerer being one of them. 
No deja importar o agregar algunas clases como la clase de hechicero.

**Comment by allnnde** [comment]
Buenas, podrias subir alguna imagen para ver bien cual es el problema?

**Comment by Keneg11** [comment]
![image](https://github.com/allnnde/pf2e-esp-translation/assets/129921373/580e65fa-a841-4535-b4dd-ef7d216526f3)

**Comment by Keneg11** [comment]
dice que se comleto pero no se agrega

**Comment by allnnde** [comment]
Buenas, hemos probado con las ultimas veriones y se ha soluionado el problema, si nos puees confirmar para cerrar el issue,
Estamos probando con las ultimas versiondes de foundry (12) y la de pathfinder (6.0.1)

**Comment by Keneg11** [comment]
muchas gracias, si ya cheque que funcionara
