### ISSUE TITLE
Problemas improtando del bestiario age of ashes

### ISSUE THREAD

**Issue by Keneg11** [allnnde/pf2e-esp-translation#208]
Hola una disculpa, encontre un problema al jalar actores del bestiario de age of ashes con el modulo activado, por alguna razon no se hace la importacion.  Ya desactivandolo se va el problema.

**Comment by allnnde** [comment]
Buenas, ya creo que esta, podrias corroborar? se probo por la versiones de
Foundry: 12,
Pathfinder 2e: 6.0.2
traduccion: 5.20.2

**Comment by Keneg11** [comment]
si ya quedo muchas gracias

**Comment by Keneg11** [comment]
si ya quedo muchas gracias
