### ISSUE TITLE
Better path resolution

### ISSUE THREAD

**Issue by vitaly-t** [allnnde/pf2e-esp-translation#209]
https://github.com/allnnde/pf2e-esp-translation/blob/aeb68c586f6d22a4df9c393dc930a054291159eb/src/helper/pack-extractor/pack-extractor.js#L625

it is better to write the code like this:

```ts
const p = resolvePath(obj, path);
if(p.exists) {
    const value = p.value; // use the value if exists
}
```

Otherwise, you are resolving all values twice ;)

**Comment by allnnde** [comment]
hola, entiendo tu punto, pero todo lo que es extraccion de los archivos es una copia de como se  hace en el repositorio del idioma aleman, por ende no voy a modificar el codigo a no ser que sea por algo critico.

Gracias por la sugerencia
