### ISSUE TITLE
Error en consola al importar el bestiario de Amenaza bajo Otari.

### ISSUE THREAD

**Issue by carlesbapeiro** [allnnde/pf2e-esp-translation#211]
Añado captura del error que saca en la consola: 

![image](https://github.com/allnnde/pf2e-esp-translation/assets/61293115/4a208c83-cc89-413b-a59a-cfa76143124e)

Al cargar la partida tambien me sale un error de Babele que puede que este relacionado: 

![image](https://github.com/allnnde/pf2e-esp-translation/assets/61293115/280ad51f-0e69-40b9-8723-c57c2eb11542)

Al desactivar el modulo , se pueden importar en ingles.

Probablemente sea el mismo problema que ocurre con #208 
Me he fijado en que solo ocurre con algunos bestiarios.

**Comment by carlesbapeiro** [comment]
He conseguido importarlo con el modulo activo modificando directamente el JavaScript en la consola. 
En translator.js 340. 

`if (actorItem) {
    if (entry.type !== "melee") {
        itemKey = `${entry.type}->${entry.name}`;
    } else {
        if (entry.system && entry.system.weaponType && entry.system.weaponType.value) {
            itemKey = `strike-${entry.system.weaponType.value}->${entry.name}`;
        } else {
            console.warn(`entry.system or entry.system.weaponType or entry.system.weaponType.value is undefined for entry:`, entry);
            itemKey = entry.name; // Fallback to a default key
        }
    }
} else {
    itemKey = entry.name;
}`

**Comment by allnnde** [comment]
Buenas, ya no salen los errores de importacion de los bestiarios, o al menos no el otari, 
hay muchas errores y advertencia en la consola, pero entiendo que son tambien de otros componentes como el de babel.get que mostras
tambien a nivel de codigo siempre estoy copiando el repo del idioma aleman que es el que mejor lo tiene hasta el momento

Foundry: 12,
Pathfinder 2e: 6.0.2
traduccion: 5.20.2

**Comment by carlesbapeiro** [comment]
Buenas @allnnde ,  con la 5.20.2 me funciona perfectamente y no sale el error. Gracias!!!
