### ISSUE TITLE
clave: Drop traducida como gota.

### ISSUE THREAD

**Issue by Eimor** [allnnde/pf2e-esp-translation#28]
Drop, en el tab de acciones de la hoja de personajes, cuando envainas o desenvainas un arma, aparece la opción de dejar caer (DROP).
Se tradujo como gota que sería una traducción literal. Pero en este caso necesitamos Dop de dejar caer o tirar.
Buscando sinonimos lo mejor que veo es "soltar".

**Comment by allnnde** [comment]
se ha solucionado en la version [4.2.13](https://github.com/allnnde/pf2e-esp-translation/releases/tag/v4.2.13)
