### ISSUE TITLE
[Feature Request] Añadir en opciones la opción de habilitar/deshabilitar las traducciones para cada jugador

### ISSUE THREAD

**Issue by Eleuis** [allnnde/pf2e-esp-translation#330]
Hola,

He observado que Babele da la funcionalidad de mostrar el nombre de la entrada del compendio en ambos idiomas con este formato [Español]/[Inglés]

Sin embargo, el contenido está únicamente en español. Tengo jugadores (y yo mismo) que prefieren utilizar el inglés pero no queremos excluir a la gente que solo habla español.

¿Es posible añadir una opción en los ajustes de foundry para que, en el lado cliente, cada jugador pueda elegir si quiere ver el compendio traducido o no? En caso de que no sea posible esta característica, ¿Sería viable hacer que también aparezca el inglés en la descripción de la entrada del compendio y no solo el nombre?

Un saludo

**Comment by allnnde** [comment]
creo que cada jugador puede en settings seleccionar el idioma que desean usar, ya que eso es algo mas del sismtea no tanto de la traduccion en si. puedo ver de averiguarlo

**Comment by Eleuis** [comment]
Hola,
No consigo reproducir este comportamiento:
![image](https://github.com/user-attachments/assets/f86adb70-5af0-4c35-ba86-6ac3bbf50555)

Como se aprecia en la imagen, el idioma de preferencia está en inglés. A pesar de ello, todos los compendios y las descripciones de cada entrada aparecen en español. Lo mismo con las habilidades de los personajes.

La versión de foundry es 12.331
La versión del sistema de pf2e es 6.4.1
La versión del módulo es 6.3.6
